/**
 * @file emu.h
 * @brief Top-level emulator object.
 *
 * Owns the cart, bus, and CPU, and drives the system one frame at a
 * time. main.c (or any other host) creates an Emu, loads a ROM, and
 * calls emu_run_frame in a loop.
 *
 * Frame pacing is the caller's responsibility -- emu_run_frame
 * advances exactly one frame's worth of cycles and returns
 * immediately. For Blargg test runs, no pacing is needed; for an
 * actual game, the host would sleep until the frame deadline.
 */
#ifndef EMU_H
#define EMU_H

#include <stdint.h>
#include <stddef.h>

typedef struct Emu Emu;

Emu* emu_create(void);
void emu_destroy(Emu* e);

/**
 * @brief Load a ROM from disk into the emulator's cart.
 *
 * Returns 0 on success, nonzero on failure (see CartResult in cart.h).
 */
int emu_load_rom(Emu* e, const char* path);

/**
 * @brief Run one frame's worth of cycles (~70224 T-cycles).
 *
 * Steps the CPU repeatedly until at least one frame's worth of
 * cycles has elapsed. May overshoot by a few cycles depending on
 * which instruction crosses the boundary; the overshoot is implicit
 * carry-over for the next frame and does not need to be tracked.
 */
void emu_run_frame(Emu* e);

/**
 * @brief Set the current state of all 8 joypad buttons.
 *
 * Convenience wrapper for joypad_set_buttons. The bitmask layout is
 * the JoypadButton enum from joypad.h: bit 0 = right, bit 1 = left,
 * bit 2 = up, bit 3 = down, bit 4 = A, bit 5 = B, bit 6 = select,
 * bit 7 = start. Bit set = held. Idempotent (per decision 029).
 */
void emu_set_buttons(Emu* e, uint8_t buttons);

/**
 * @brief Pointer to the current framebuffer (PPU output).
 *
 * 144 rows of 160 bytes each, row-major. Each byte is a 0-3 grayscale
 * index. Caller does not own; the buffer remains valid for the
 * lifetime of the Emu.
 */
const uint8_t* emu_framebuffer(const Emu* e);

/**
 * @brief Pull mono signed 16-bit audio samples generated by the APU.
 *
 * Returns the number of samples copied. If fewer samples are available
 * than requested, the caller should fill the rest with silence.
 */
size_t emu_audio_read(Emu* e, int16_t* out, size_t max_samples);

#endif